#!/bin/bash

# update
sudo apt-get update && sudo apt-get dist-upgrade -y
sudo apt install python3 python3-venv -y

#create virtualenv
python3 -m venv env

#start virtualenv
source env/bin/activate

#install packages
sudo -H pip3 install -r requirements.txt

#run
sudo python3 flask_app.py
